#include "metals.inc"
#declare GearBody_material = material { 
	texture { Chrome_Metal
	}
}

#declare Marker_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

#declare Num1_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

#declare Num2_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

#declare Num3_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

#declare Num4_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

#declare Num5_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

#declare Num6_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

#declare Num7_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

#declare Num0_material = material { 
	texture { 
		pigment { color Black }
	finish {
	ambient 0.35
brilliance 2
diffuse 0.3
metallic
specular 0.80
roughness 1/20
reflection 0.1	}
	}
}

